resolver: lts-18.8

packages:
- xmobar.git

extra-deps:
- iwlib-0.1.0
# - libmpd-0.9.2.0

flags:
  xmobar:
    with_threaded: true
    with_rtsopts: true
    all_extensions: true
    with_iwlib: true
    with_dbus: true
